version: "2"
linters:
  default: "all"
  disable:
    - forbidigo
    - wrapcheck
    - varnamelen
    - ireturn
    - nlreturn
    - gochecknoglobals
    - gosec
    - nestif
    - depguard
    - exhaustruct
    - wsl
    - tagliatelle
    - revive
  settings:
    lll:
      line-length: 120
    cyclop:
      max-complexity: 15
formatters:
  settings:
    goimports:
      local-prefixes:
        - github.com/vitoordaz/dynd
